### ISSUE TITLE
download API for VDJServer

### ISSUE THREAD

**Issue by schristley** [ireceptor-plus/WP2#10]
It's still unclear how long it will take for Tapis to provide VDJServer with an async query API which can download whole query datasets in one shot. I'm thinking of writing an API, to be used in the short-term, that can be used purely for downloads. If I do that, is the gateway (@bcorrie ) willing to use it?

The idea is for it to be an asynch API that would transition to the real async query when it becomes available. It would be limited in scope, but that makes it doable. I know we've talked for awhile about an asynch API. I kind of feel we should move forward with a prototype even though Tapis hasn't provided one yet.

**Comment by bcorrie** [comment]
We would definitely consider it, as our current mechanism is very clunky. We currently have use a synchronous download from N repositories in parallel, with the VDJServer looping over the data 1000 rearrangements at a time. It might be tricky to put an asynchronous download into that process, but it might be possible to use the asynchronous mechanism for VDJServer and put a synchronous wrapper around it on the Gateway end??? We need to bring @jeromejaglale into the discussion 8-)

**Comment by bcorrie** [comment]
@schristley do you want to re-open this issue in https://github.com/ireceptor-plus/specifications/projects/3 and close it here?

**Comment by schristley** [comment]
see https://github.com/ireceptor-plus/specifications/issues/33
