### ISSUE TITLE
Please enable CORS for IPA repositories to allow web browser requests

### ISSUE THREAD

**Issue by schristley** [ireceptor-plus/WP2#13]
When issuing a request to IPA1 ADC API from a web browser, I get a `Preflight response is not successful` error from the browser. This is security thing with browsers whereby if JavaScript code sends a http request that's to a different server (origin) then it asks that server if such Cross-Origin Resource Sharing ([CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)) requests are allowed. The browser typically sends an http OPTIONS request (that's the "preflight" message from Safari) to test that the server accepts. For example, VDJServer's API has CORS enabled with code like this:

```
// CORS
var allowCrossDomain = function(request, response, next) {
    response.header('Access-Control-Allow-Origin', '*');
    response.header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE,OPTIONS');
    response.header('Access-Control-Allow-Headers', 'Content-Type, Authorization, Content-Length, X-Requested-With');

    // intercept OPTIONS method
    if ('OPTIONS' === request.method) {
        response.status(200).end();
    }
    else {
        next();
    }
};
```

Can you enable CORS on your IPA repositories? The basic idea is that the server needs to send back some headers to say what is allowed. Here's some [info](https://stackoverflow.com/questions/8719276/cross-origin-request-headerscors-with-php-headers) about doing it for php. Make sure to allow at least OPTIONS, GET and POST.

As VDJServer uses JavaScript in the browser, it needs this enabled so that it can perform queries to the ADC API, Stats API, etc., on the IPA repositories.

**Comment by schristley** [comment]
It seems partially enabled, because I'm able to send a GET request to the /info end point and get a response, but a POST to the /repertoire end point fails.

**Comment by bcorrie** [comment]
@schristley is this just going to the /info entry point?

Can you test on either http://ipa5.ireceptor.org/airr/v1/info or one of the COVID's (http://covid19-1.ireceptor.org/airr/v1/info).

The later are iReceptor Turnkey repositories while ipa1-ipa4 are our older PHP service. The code base is the same, but the PHP configs might be different... Want to eliminate that variable...

**Comment by bcorrie** [comment]
Opps, I see that this is for the Repertoire end point...

Can you try these...

http://covid19-2.ireceptor.org/airr/v1/repertoire/5ef386a30255b55fcc1bf5eb
https://ipa1.ireceptor.org/airr/v1/repertoire/4

They work for me as a URL in my browser.

Do either of them work for you in your situation?

**Comment by schristley** [comment]
> @schristley is this just going to the /info entry point?

@bcorrie It's needed for all of the entry points, for both GET and POST methods.

> Can you test on either http://ipa5.ireceptor.org/airr/v1/info or one of the COVID's (http://covid19-1.ireceptor.org/airr/v1/info).

I'll give them a try.

**Comment by schristley** [comment]
> Can you test on either http://ipa5.ireceptor.org/airr/v1/info or one of the COVID's (http://covid19-1.ireceptor.org/airr/v1/info).

Both of these give errors for /info and for /repertoire

> They work for me as a URL in my browser.

CORS isn't for when a URL is entered directly into the browser. It's when JavaScript uses AJAX to perform an http request in the background. Code looks something like this:

<script>
        var jqxhr = $.ajax({
            type: 'GET',
            contentType: 'application/json',
            url: 'http://ipa5.ireceptor.org/airr/v1/info',
        });
</script>

We are going to need this on the Stats API as well...

If @jeromejaglale is not sure about how to setup it up, it might be worthwhile to have a chat. It's relatively simple, the server just needs to send back some specific http headers in the response, but I'm not familiar enough with the Turnkey php to know where that goes...

**Comment by bcorrie** [comment]
I thought we had CORS enabled on the Turnkey, so thought that the problem might be on the older PHP software stack.

@jeromejaglale @bzimonja can you comment?

**Comment by bzimonja** [comment]
I'll have to start digging through our JIRA issues, I remember setting up CORS ages ago but maybe something changed in PHP or Apache so it needs another way...

**Comment by bzimonja** [comment]
@schristley Can you try our stats staging server? When I did

curl -H "Origin:http://test.com" --verbose https://stats-staging.ireceptor.org/airr/v1/repertoire -d '{"fields":["repertoire_id"]}'

I returned the repertire_id list with the following in the header:
`< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: origin, x-requested-with, content-type
< Access-Control-Allow-Methods: GET, POST`

Which I think means CORS is enabled for those methods. Or is there additional stuff to do for JS queries?

**Comment by schristley** [comment]
@bzimonja It partially works, it is similar to IPA1 in that the /info returns data but /repertoire gets the "preflight" error. To properly simulate the preflight, do this command:

```
curl -X OPTIONS -H "Origin:http://test.com" --verbose https://stats-staging.ireceptor.org/airr/v1/repertoire
```

It does return the correct CORS headers but it returns HTTP status 400, so the browser considers it to have failed. The issue is that your CORS code has to trap the "OPTIONS" method and return HTTP status 200, along with the headers.

**Comment by bzimonja** [comment]
This is an unrelated issue I think  - based on the API design when I started it, I made the JSON file required or it returns an error. If you add 

-d '{"fields":["repertoire_id"]}'

to the curl, I get 

HTTP/1.1 200 OK

I understand we can make /repertoire not require any JSON and return everything but what about /rearrangement? A stray request could download the entire database...

**Comment by schristley** [comment]
> This is an unrelated issue I think - based on the API design when I started it, I made the JSON file required or it returns an error. If you add

You are confusing the POST method with the OPTIONS method. There is no data sent with OPTIONS, the server is not suppose to execute a query or anything like that. If the server tries to interpret data for OPTIONS, that is incorrect. OPTIONS is like a GET and the browser sends it simply to get a 200 response and check for the CORS headers. The browser doesn't expect any data back except for the response headers.

**Comment by bzimonja** [comment]
OK, try now - I added a check that says "if there's no JSON on repertoire request, treat it as an empty JSON file" and the curl works.

**Comment by schristley** [comment]
> OK, try now - I added a check that says "if there's no JSON on repertoire request, treat it as an empty JSON file" and the curl works.

But it does a query and send back data, it's not suppose to do that for OPTIONS.

Isn't there a way for you to check what the http method is, something like this code?

```
if request.method == 'OPTIONS' then
  return 200
else if request.method == 'POST' then
  do query
```

**Comment by schristley** [comment]
> OK, try now - I added a check that says "if there's no JSON on repertoire request, treat it as an empty JSON file" and the curl works.

Yes, it does work, but it's dangerous for /rearrangement. The browser will try to download the whole database when it sends the OPTIONS request...

**Comment by bzimonja** [comment]
Ah yes, sorry, was indeed confused! Apologies!

I've added the method check, and now there's no data, just a 200 response. Can you give it a try again?

**Comment by schristley** [comment]
I tried searching in the PHP code for the header name `Access-Control-Allow-Origin` but I couldn't find it. Maybe it isn't being set in PHP but in Apache? Are the headers being set in httpd.conf?

**Comment by bzimonja** [comment]
Yes, CORS have been set in conf files for each server:

  Header set  Access-Control-Allow-Origin "*"
  Header set Access-Control-Allow-Headers "origin, x-requested-with, content-type"
Header set Access-Control-Allow-Methods "GET, POST, OPTIONS"

**Comment by schristley** [comment]
> Ah yes, sorry, was indeed confused! Apologies!
> 
> I've added the method check, and now there's no data, just a 200 response. Can you give it a try again?

Yes, that works, for /repertoire though not for /rearrangement which returns a 400 status. While /info still returns data with OPTIONS. So you have to manually handle it for each end point? Hopefully, there is a simple way to do that for all end points in one place...

**Comment by schristley** [comment]
> Yes, CORS have been set in conf files for each server:
> 
> Header set Access-Control-Allow-Origin "*"
> Header set Access-Control-Allow-Headers "origin, x-requested-with, content-type"
> Header set Access-Control-Allow-Methods "GET, POST, OPTIONS"

Ah, okay, you try to handle OPTIONS in Apache then. If you have mod_rewrite enabled then a few lines should do it.

https://stackoverflow.com/questions/25709175/handling-cors-preflight-request-in-apache

```
RewriteEngine On                  
RewriteCond %{REQUEST_METHOD} OPTIONS 
RewriteRule ^(.*)$ $1 [R=200,L]    
```

**Comment by schristley** [comment]
Actually I guess this might be better

https://stackoverflow.com/questions/27703871/return-empty-response-from-apache/

```
RewriteCond %{REQUEST_METHOD} OPTIONS
RewriteRule ^(.*)$ $1 [R=204,L]
```

**Comment by bzimonja** [comment]
Oh thank you! I was able to add it to the other Rewrite directives in our app directory (public/.htaccess) and it looks like it works, with 204 rewrite.

**Comment by schristley** [comment]
Better, but it's not returning the CORS headers now...

**Comment by schristley** [comment]
Maybe add `always` for the headers

```
Header always set Access-Control-Allow-Origin "*"                   
Header always set Access-Control-Allow-Methods "POST, GET, OPTIONS"
```

**Comment by bzimonja** [comment]
Another good catch, they should be back! 👍

**Comment by schristley** [comment]
Always there, forgot there are 3 headers!

```
Header always set Access-Control-Allow-Origin "*"                   
Header always set Access-Control-Allow-Headers "origin, x-requested-with, content-type"
Header always set Access-Control-Allow-Methods "POST, GET, OPTIONS"
```

**Comment by bzimonja** [comment]
Are those the only three? I now re-enabled them all, we used to have them before rewrite mucked them up :)

**Comment by schristley** [comment]
it works!

**Comment by schristley** [comment]
@bcorrie Let me know when you are able to roll out those config changes to all the repositories. I'll double check that they all work, and we can close this.

**Comment by bzimonja** [comment]
I'm still trying to figure if I can get the Rewrite rules into .conf, or headers into .htaccess, so we only need to make one change. But if not, we'll do it in two places...

**Comment by bzimonja** [comment]
@schristley I've updated all the iReceptor repositories, can you please check they work on your end when you have the time?

**Comment by schristley** [comment]
@bzimonja Works! I checked ipa1 to 5 and covid19-1 to 4, and they all responded properly. It's correct that ipa1 to 4 is HTTPS while ipa5 and covid19-1 to 4 are HTTP?

**Comment by bzimonja** [comment]
Yes, we can't figure a good way to package an SSL cert with a turnkey that will run on any domain, so we use http for now.
