### ISSUE TITLE
VDJServer queries slow down with increasing "from" parameter

### ISSUE THREAD

**Issue by schristley** [ireceptor-plus/WP2#8]

**Comment by schristley** [comment]
This seems to be an inherent issue with `skip` in Mongo. According to the mongo doc:

> The cursor.skip() method requires the server to scan from the beginning of the input results set before beginning to return results. As the offset increases, cursor.skip() will become slower

Mostly they suggest to alter the queries, e.g. to use a field like `_id` as a unique index, remember the `_id` from the previous query and start there for the next query. The problem with these workarounds is that the ADC API is stateless, so you don't have the `_id` from the last query in order to use it for a new query.

**Comment by schristley** [comment]
@bcorrie It seems clear that doing downloads with `from` paging through the results isn't practical except for small result sets. I think we should consider designing a "download" API as an extension to the ADC API that allows repositories to handle large data requests.

**Comment by bcorrie** [comment]
Do you think we need a new API for this, or would the LRQ capability on the VDJServer back end meet this need? The IPA/Turnkey software seems to handle these large downloads OK with our current network stream approach, even though they do take a long time. I think that is what the LRQ capability for VDJServer would give you, correct? You could do an LRQ, download to a file, and then write the output to the client. This would mean having the connection open the whole time.

Or are you thinking that the new ADC API would be an asynchronous API where you ask for a download, get notified when it is ready, and then go do a file transfer? So the connection doesn't remain open while the query is being done?

**Comment by schristley** [comment]
> This would mean having the connection open the whole time.

From a purely theoretical aspect, this can satisfy the ADC API, but I don't think it's a good idea from a practical standpoint.

> handle these large downloads OK with our current network stream approach

Unfortunately, this streaming approach is not available to VDJServer, which is why we need the LRQ.
> Or are you thinking that the new ADC API would be an asynchronous API where you ask for a download, get notified when it is ready, and then go do a file transfer? So the connection doesn't remain open while the query is being done?

Correct. We had talked previously in the CRWG about an asynchronous API, but it wasn't clear if it was needed. Now with VDJServer, we have an actual implementation where the synchronous API is less than ideal.

**Comment by bcorrie** [comment]
> > This would mean having the connection open the whole time.
> 
> From a purely theoretical aspect, this can satisfy the ADC API, but I don't think it's a good idea from a practical standpoint.

It has its limitations, for sure, but it does work. So it is practical for many downloads, in particular because of its simplicity and ease of use. You ask for data and you get it 8-)

I agree it may cause problems for large downloads, in particular if you have a bad network connection. So I don't disagree that an asynchronous API would also be useful. I just wanted to point out that for us this stream approach is a practical and functional download implementation, even for quite large downloads.

> > handle these large downloads OK with our current network stream approach
> 
> Unfortunately, this streaming approach is not available to VDJServer, which is why we need the LRQ.

My point was that if you had LRQ you could provide such a streaming implementation. Not saying you want to or should, but I suspect you could.

> > Or are you thinking that the new ADC API would be an asynchronous API where you ask for a download, get notified when it is ready, and then go do a file transfer? So the connection doesn't remain open while the query is being done?
> 
> Correct. We had talked previously in the CRWG about an asynchronous API, but it wasn't clear if it was needed. Now with VDJServer, we have an actual implementation where the synchronous API is less than ideal.

Should we create an issue for this in either the AIRR CRWG or AIRR Standards Github? I think one of our main concerns about this was that it requires repositories to implement a relatively complex API, so we didn't want to do it unless we needed it. It sounds like maybe we need it 8-)

**Comment by schristley** [comment]
> Should we create an issue for this in either the AIRR CRWG or AIRR Standards Github? I think one of our main concerns about this was that it requires repositories to implement a relatively complex API, so we didn't want to do it unless we needed it. It sounds like maybe we need it 8-)

Sure. I'm thinking of it as an optional extension versus mandatory. I'm not sure how we designate that though.

**Comment by schristley** [comment]
see https://github.com/ireceptor-plus/specifications/issues/33
