### ISSUE TITLE
VDJServer parsing rules for gene and subgroup

### ISSUE THREAD

**Issue by schristley** [ireceptor-plus/WP2#9]
VDJServer has slightly different parsing rules from IPA to generate the gene and subgroup.

From Brian:

> We assign both, subgroup is everything to the left of -, gene is everything to the left of *, assuming IMGT nomencalutre for the v_call

And in the case of genes that don't have -, the subgroup is everything left of *. This is how VDJServer is different as it wasn't assigning the subgroup if the - was missing.

**Comment by bussec** [comment]
@schristley When does this occur? For gene with the "S" nomenclature ("IGHV1S23")? According to IMGT's specs, in this case the "S" should be separator.

**Comment by schristley** [comment]
@bussec For VDJServer, this is done during data load. I believe @bcorrie said that IPA does it during data load too.

Even though these fields aren't in the AIRR Schema, Brian and I have a "gentleman's agreement" that we will have them in as custom fields so the Gateway GUI can do optimized queries on them.

I'm unsure about the "S" nomenclature. We should probably find some studies currently in the ADC that have those genes so we can investigate. I'm guessing on the VDJServer side that they don't have the gene and subgroup. Not sure about IPA.

**Comment by schristley** [comment]
When I do a [search](https://gateway.ireceptor.org/sequences?query_id=17604) on IGHV1S23 in the Gateway, it returns no results...

**Comment by bussec** [comment]
> When I do a search on IGHV1S23 in the Gateway, it returns no results...

That's possible, I just invented that one, as I am really bad in human V genes ;-)

**Comment by schristley** [comment]
I browsed through the whole IGHV [table](http://www.imgt.org/IMGTrepertoire/index.php?section=LocusGenes&repertoire=genetable&species=human&group=IGHV) at imgt and none of the genes have a "S" in their name, so maybe they cleaned them up, or maybe it's a different locus.

**Comment by schristley** [comment]
ah ha, it's in the [mouse genes](http://www.imgt.org/IMGTrepertoire/index.php?section=LocusGenes&repertoire=genetable&species=Mus_musculus&group=IGHV)

**Comment by schristley** [comment]
just a test, pardon the spam

**Comment by schristley** [comment]
The VDJServer DB now available on the iReceptor Gateway has the subgroup defined. Also handle the "S" as a separator for mouse genes.
